import Link from "next/link";
import { notFound } from "next/navigation";
import { Icon } from "../../../components/Icons";

const toolContent: Record<string, { title: string; icon: string; intro: string; faqs: [string, string][] }> = {
  car: { title: "Car affordability calculator", icon: "car", intro: "A car is more than the sticker price. Check the monthly commitment, cash you keep back, and the buffer you’ll have for real life.", faqs: [["How much car can I afford in India?", "A comfortable car budget depends on your income, existing debt, savings, and the emergency fund you want to protect. Use the calculator to see a range rather than a single rule."], ["Should I buy a car in cash or on EMI?", "Cash avoids interest but can drain your safety net. EMI preserves cash but adds a monthly commitment and total financing cost. Compare both with the same inputs."]] },
  home: { title: "Home affordability calculator", icon: "home", intro: "See a home price through the lens of your down payment, loan commitment, monthly buffer, and emergency runway.", faqs: [["How much down payment should I make?", "A larger down payment can reduce the loan and interest cost, but not if it leaves you without accessible emergency savings."], ["Does this include every cost of buying a home?", "It is a planning estimate. Add maintenance, registration, taxes, insurance, and other local costs before making a final decision."]] },
  phone: { title: "Phone affordability calculator", icon: "phone", intro: "Before you upgrade, see whether the full price fits your current plan—or whether a less expensive option buys you more breathing room.", faqs: [["Is phone EMI actually cheaper?", "EMI can preserve cash, but it can also cost more overall. Enter the rate and tenure to see the full repayment, not only the monthly number."], ["What is a safe phone budget?", "One that does not compromise your emergency fund or force you to carry high-cost debt. Your own inputs matter more than a universal percentage."]] },
  laptop: { title: "Laptop affordability calculator", icon: "laptop", intro: "Plan a laptop purchase around your work, study, or creative needs without turning a useful upgrade into monthly stress.", faqs: [["Should I buy a laptop with savings?", "Keep a safety floor in place first. A cash purchase is only comfortable if the remaining savings still cover the buffer you selected."], ["Does the calculator recommend specific laptops?", "The product area is designed for curated or affiliate data. Live prices should always be verified with the retailer."]] },
  vacation: { title: "Vacation budget calculator", icon: "plane", intro: "A trip should include more than the flight. Build a realistic budget for travel, hotel, food, activities, and the unexpected.", faqs: [["Should I use an EMI for a vacation?", "Financing a holiday can turn a short experience into a long commitment. Compare the total repayment with a wait-and-save scenario."], ["How much emergency money should I take?", "Keep your regular emergency fund separate. Add a trip-specific contingency amount for changes, health, or delays."]] },
  "student-loan": { title: "Student loan affordability calculator", icon: "graduation", intro: "Understand the loan amount, repayment period, and monthly commitment behind an education decision.", faqs: [["Is education debt always worth it?", "The answer depends on course cost, expected career options, repayment terms, and your wider financial plan. This tool makes the payment visible."], ["Are student loan rates fixed?", "Terms vary by lender and product. Use the rate you were actually quoted and verify the final agreement."]] }
  ,"personal-loan": { title: "Personal loan calculator", icon: "spark", intro: "Make the full repayment visible before a personal loan becomes another fixed commitment in your month.", faqs: [["What should I compare on a personal loan?", "Compare the total repayment, rate, processing fees, tenure, and the monthly buffer left after every existing commitment."], ["Can a lower EMI be more expensive?", "Yes. A longer tenure can reduce the monthly payment while increasing the total interest paid."]] },
  general: { title: "General purchase affordability calculator", icon: "chart", intro: "For the purchase that does not fit a neat category, use the same honest framework: cash flow, savings, debt, and timing.", faqs: [["What can I use this calculator for?", "Furniture, electronics, a wedding, a relocation, or any other large purchase where the price alone does not tell the whole story."], ["What if I do not know every number?", "Use a conservative estimate and keep the assumptions visible. You can come back and refine the result later."]] }
};

export function generateStaticParams() { return Object.keys(toolContent).map((slug) => ({ slug })); }

export default function ToolPage({ params }: { params: { slug: string } }) {
  const tool = toolContent[params.slug];
  if (!tool) notFound();
  return <main className="tool-page-shell"><div className="page-hero"><span className="category-icon"><Icon name={tool.icon} size={26} /></span><p className="eyebrow" style={{ marginTop: 24 }}>India · INR · private by default</p><h1>{tool.title}</h1><p>{tool.intro}</p><Link href="/#calculator" className="button button-primary" style={{ marginTop: 20 }}>Open the calculator <Icon name="arrow" size={16} /></Link></div><section className="section section-soft"><div className="section-heading"><div><p className="eyebrow">How to use it</p><h2>Make the real cost<br /><em>easy to see.</em></h2></div><p>Use estimates if you need to. The important thing is to make the assumptions visible before you commit.</p></div><div className="feature-row"><div className="feature-card"><div className="feature-icon">01</div><h3>Start with your monthly life</h3><p>Income, essential spending, debt, and savings establish the room you actually have.</p></div><div className="feature-card"><div className="feature-icon">02</div><h3>Add the purchase details</h3><p>Cash, EMI, down payment, interest, and tenure change the answer significantly.</p></div><div className="feature-card"><div className="feature-icon">03</div><h3>Read the why, not just the label</h3><p>Use the score, reasons, and safer alternatives as decision support—not a guarantee.</p></div></div></section><section className="section"><div className="section-heading"><div><p className="eyebrow">Frequently asked</p><h2>Questions about<br /><em>{tool.title.split(" ")[0]}.</em></h2></div></div><div className="faq-grid">{tool.faqs.map(([question, answer]) => <details className="faq-item" key={question}><summary>{question}</summary><p>{answer}</p></details>)}</div></section></main>;
}
